# Generated by Django 3.1.3 on 2020-11-06 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='price',
        ),
        migrations.AddField(
            model_name='form',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'Mechanical'), ('CE', 'Civil')], default='CSE', max_length=3),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator(code=None, message='Enter a valid Email address', whitelist=None)]),
        ),
        migrations.AddField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='form',
            name='mobile',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(10, 'Enter a valid number'), django.core.validators.MaxLengthValidator(13, message='Enter a valid number')]),
        ),
        migrations.AddField(
            model_name='form',
            name='rollno',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(8, message='Enter valid Roll no in the format 19CS8179')]),
        ),
        migrations.AddField(
            model_name='form',
            name='website',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator(schemes=None)]),
        ),
    ]
