# Generated by Django 3.1.3 on 2020-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20201106_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='form',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CH', 'Chemical Engineering'), ('BT', 'BioTechnology')], default='CSE', max_length=3),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='form',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='rollno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
