# Generated by Django 3.1.3 on 2020-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20201106_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('CH', 'Chemical Engineering'), ('BT', 'BioTechnology')], max_length=3),
        ),
        migrations.AlterField(
            model_name='form',
            name='content_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1),
        ),
    ]
