# Generated by Django 3.1.3 on 2020-11-07 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20201107_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='form',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='form',
            name='branch',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('BioTechnology', 'BioTechnology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='form',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=None)]),
        ),
    ]
