# Generated by Django 3.1.3 on 2020-11-08 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20201107_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='mobile',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Enter a valid 10 digit mobile number'), django.core.validators.MaxLengthValidator(10, 'Enter a valid 10 digit mobile number')]),
        ),
    ]
