# Generated by Django 3.1.3 on 2020-11-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20201108_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
    ]
