# Generated by Django 3.1.3 on 2020-11-08 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20201108_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referral'),
        ),
        migrations.AddField(
            model_name='profile',
            name='codechef',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=None)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=None)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Enter a valid 10 digit mobile number'), django.core.validators.MaxLengthValidator(10, 'Enter a valid 10 digit mobile number')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Enter Full Name')], verbose_name='Name'),
        ),
    ]
