# Generated by Django 3.1.3 on 2020-11-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_auto_20201110_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myauth.state'),
        ),
    ]
